/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#00a572',
        'on-tertiary-container': '#00311f',
        'tertiary-fixed-dim': '#4edea3',
        'on-primary-fixed': '#23005c',
        'surface-container-lowest': '#090e18',
        'surface-tint': '#d0bcff',
        primary: '#d0bcff',
        'on-tertiary': '#003824',
        'outline-variant': '#494454',
        'error-container': '#93000a',
        'secondary-fixed': '#e1e0ff',
        'on-background': '#dee2f1',
        tertiary: '#4edea3',
        'surface-dim': '#0e131d',
        'secondary-container': '#3131c0',
        'inverse-on-surface': '#2b303b',
        'surface-container-low': '#171c26',
        outline: '#958ea0',
        error: '#ffb4ab',
        surface: '#0e131d',
        'on-surface': '#dee2f1',
        background: '#0e131d',
        'inverse-surface': '#dee2f1',
        'tertiary-fixed': '#6ffbbe',
        'surface-container': '#1b202a',
        'on-primary': '#3c0091',
        'surface-variant': '#303540',
        'on-secondary-fixed': '#07006c',
        'secondary-fixed-dim': '#c0c1ff',
        'surface-container-highest': '#303540',
        'on-surface-variant': '#cbc3d7',
        'on-secondary': '#1000a9',
        'surface-bright': '#343944',
        'on-error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#2f2ebe',
        'on-error': '#690005',
        'primary-fixed': '#e9ddff',
        'surface-container-high': '#252a35',
        'on-tertiary-fixed': '#002113',
        'on-secondary-container': '#b0b2ff',
        'on-tertiary-fixed-variant': '#005236',
        'on-primary-container': '#340080',
        secondary: '#c0c1ff',
        'inverse-primary': '#6d3bd7',
        'primary-container': '#a078ff',
        'on-primary-fixed-variant': '#5516be',
        'primary-fixed-dim': '#d0bcff'
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px'
      },
      spacing: {
        'space-3xs': '0.125rem',
        'space-xs': '0.375rem',
        'gutter-mobile': '0.25rem',
        'space-2xs': '0.25rem',
        'space-md': '0.75rem',
        margin: '1rem',
        'margin-mobile': '0.5rem',
        'space-sm': '0.5rem',
        'space-xl': '1.5rem',
        'space-lg': '1rem',
        gutter: '0.5rem'
      },
      fontFamily: {
        'code-sm': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'data-lg': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'kpi-micro': ['JetBrains Mono', 'monospace'],
        'body-regular': ['JetBrains Mono', 'monospace'],
        'display-xl-mobile': ['Space Grotesk', 'sans-serif'],
        'body-compact': ['JetBrains Mono', 'monospace'],
        'display-xl': ['Space Grotesk', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace']
      },
      fontSize: {
        'code-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg': ['20px', { lineHeight: '26px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'data-lg': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['16px', { lineHeight: '22px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'kpi-micro': ['9px', { lineHeight: '11px', letterSpacing: '0.1em', fontWeight: '700' }],
        'body-regular': ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'display-xl-mobile': ['24px', { lineHeight: '30px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-compact': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '400' }],
        'display-xl': ['32px', { lineHeight: '38px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'label-caps': ['10px', { lineHeight: '12px', letterSpacing: '0.08em', fontWeight: '700' }]
      }
    }
  },
  plugins: []
};
